"""empty message

Revision ID: 10a8fbb44798
Revises: 526478175864
Create Date: 2022-05-18 08:15:59.808253

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '10a8fbb44798'
down_revision = '526478175864'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('person', sa.Column('completed', sa.Boolean(), nullable=True))
    op.execute('UPDATE person SET completed = False WHERE completed is NULL;')
    op.alter_column('person', 'completed', nullable=False)
    op.alter_column('person', 'address',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('person', 'address',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('person', 'completed')
    # ### end Alembic commands ###
