"""empty message

Revision ID: 526478175864
Revises: 
Create Date: 2022-05-18 07:41:12.573720

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '526478175864'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('person', sa.Column('address', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('person', 'address')
    # ### end Alembic commands ###
